Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/ClassLength:
  Description: 'Avoid classes longer than 100 lines of code.'
  Enabled: false
  CountComments: false  # count full line comments?
  Max: 100

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/MethodLength:
  Description: 'Avoid methods longer than 10 lines of code.'
  Enabled: false
  CountComments: false  # count full line comments?
  Max: 10

Style/ClassVars:
  Description: 'Avoid the use of class variables.'
  Enabled: false

Style/Documentation:
  Description: 'Document classes and non-namespace modules.'
  Enabled: false
